### ISSUE TITLE
Optimize Login Page Design.

### ISSUE THREAD

**Issue by bhaveshgarg2000** [huamanraj/Covid_website#11]
#Issue Title:
Give it a clear and concise title like "Optimize Login Page Design."

**Comment by Rhythmshah21** [comment]
@bhaveshgarg2000 i would like to work on this issue

**Comment by bhaveshgarg2000** [comment]
Hi @huamanraj Please Assign this issue to me

**Comment by huamanraj** [comment]
sure! work on it!

**Comment by bhaveshgarg2000** [comment]
Hii @huamanraj Please check PR related to this issue
